### ISSUE TITLE
series

### ISSUE THREAD

**Issue by qwestim** [ejatapibeda/JaMovies#3]
i actually dk if it's intended but it's not giving links for series. appreciate you fixing it tho. thanks

**Comment by ejatapibeda** [comment]
fixed you can close this issues if it worked

**Comment by napacia** [comment]
it's working now, what a life saver! thanks so much 🙇🏻‍♀️

**Comment by qwestim** [comment]
> fixed you can close this issues if it worked

yap thank u rlly
