### ISSUE TITLE
Can you default to vidsrc.me first?

### ISSUE THREAD

**Issue by oathzed** [ejatapibeda/JaMovies#4]
I noticed that the code is to start with vidsrc.to but for some reason it won't initiate vidsrc.me if a video isn't found.

This show S1E1 is available on vidsrc.me but not vidsrx.to.

https://www.themoviedb.org/tv/203123-down-for-love/season/1/episode/1

For some reason, it won't scrape the episode from vidsrc.me on stremio

Thanks!

**Comment by ejatapibeda** [comment]
the vidsrc.me api currently down, and i dont have time to fix it, maybe after my exam finish ill fix this

**Comment by oathzed** [comment]
> the vidsrc.me api currently down, and i dont have time to fix it, maybe after my exam finish ill fix this

Ahh ok, that sounds good. Thank you and good luck on your exams

**Comment by oathzed** [comment]
Great job on getting this show to pull :).

Is it possible, when you have time, to make the best quality at the top? :o
![Screenshot_20240531-000201](https://github.com/ejatapibeda/JaMovies/assets/52545913/1bea37de-901d-484b-890c-fd75804022a7)

**Comment by ejatapibeda** [comment]
> Great job on getting this show to pull :).
> 
> Is it possible, when you have time, to make the best quality at the top? :o ![Screenshot_20240531-000201](https://private-user-images.githubusercontent.com/52545913/335476479-1bea37de-901d-484b-890c-fd75804022a7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxNzQ3MTEsIm5iZiI6MTcxNzE3NDQxMSwicGF0aCI6Ii81MjU0NTkxMy8zMzU0NzY0NzktMWJlYTM3ZGUtOTAxZC00ODRiLTg5MGMtZmQ3NTgwNDAyMmE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMxVDE2NTMzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAxZjAzZTc0M2M0ZDRlYjY2NmZkMWU2NmIwOTdjMGFkMzM5MmFmNzcxMzVmYjEzYjg5OGRkNWI1NWRkYzA1NmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uRV2OHdo61-dGQPrRfXmP1SA4kzN8fqcV2LRD7nyYAs)

done implemented

**Comment by oathzed** [comment]
> > Great job on getting this show to pull :).
> > Is it possible, when you have time, to make the best quality at the top? :o ![Screenshot_20240531-000201](https://private-user-images.githubusercontent.com/52545913/335476479-1bea37de-901d-484b-890c-fd75804022a7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxNzQ3MTEsIm5iZiI6MTcxNzE3NDQxMSwicGF0aCI6Ii81MjU0NTkxMy8zMzU0NzY0NzktMWJlYTM3ZGUtOTAxZC00ODRiLTg5MGMtZmQ3NTgwNDAyMmE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMxVDE2NTMzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAxZjAzZTc0M2M0ZDRlYjY2NmZkMWU2NmIwOTdjMGFkMzM5MmFmNzcxMzVmYjEzYjg5OGRkNWI1NWRkYzA1NmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uRV2OHdo61-dGQPrRfXmP1SA4kzN8fqcV2LRD7nyYAs)
> 
> done implemented

Tysm!

Closing issue

**Comment by oathzed** [comment]
@ejatapibeda hey man, how are you pulling the 4k links, looking at that nsbx provider, it's using this API?

https://vidsrc-api-bice.vercel.app/746036

But I'm only seeing 1 link show up

**Comment by ejatapibeda** [comment]
> @ejatapibeda hey man, how are you pulling the 4k links, looking at that nsbx provider, it's using this API?
> 
> https://vidsrc-api-bice.vercel.app/746036
> 
> But I'm only seeing 1 link show up

im using package not api for nsbx

**Comment by oathzed** [comment]
> > @ejatapibeda hey man, how are you pulling the 4k links, looking at that nsbx provider, it's using this API?
> > https://vidsrc-api-bice.vercel.app/746036
> > But I'm only seeing 1 link show up
> 
> im using package not api for nsbx

Oh I see it now. Thank you sir
