### ISSUE TITLE
selecting quality

### ISSUE THREAD

**Issue by napacia** [ejatapibeda/JaMovies#5]
Hi! I was wondering if there's a way for us to manually select the quality instead of it being automatic? If I remember correctly, it had this feature wayyyy back, but it was available for only a day or two before reverting to the way it used to be. Thanks!

**Comment by ejatapibeda** [comment]
the api is't updated and i dont have time to fix it, maybe after my exam finish ill fix this

**Comment by napacia** [comment]
alright, take your time. thank u and goodluck :>>

**Comment by ejatapibeda** [comment]
> alright, take your time. thank u and goodluck :>>

selecting quality now work but with different provider, ill make other update soon

**Comment by napacia** [comment]
It works great! Thank you so much. I really appreciate it. Looking forward to the next update 😊
